name: TxCrates
main: me.txs.txcrates.TxCrates
version: 1.0
authors: [Jereds]
api-version: 1.16
soft-depend: [Vault]
depend: [ContainerAPI]
commands:
  createcrate:
    usage: /createcrate <display>
    aliases: [makecrate, crates, addcrate, cratecreate]
  crate:
    usage: /crate <crate id>
    description: Gives you the specified crate.
    aliases: [txcrate]
  cratekey:
    usage: /cratekey <player> <crate id> [amount]
    description: Gives the specified player the specified crate key for that crate.
    aliases: [key, txkey]
  cratekeyall:
    usage: /cratekeyall <crate id> [amount]
    description: Gives all online players the specified crate key for that crate.
    aliases: [keyall, txkeyall]
  testhex:
    usage: /testhex <string> <from> <to>
    description: just do it
    aliases: [th]
  claimkeys:
    usage: /claimkeys
    description: claim outstanding crate keys.
    aliases: [ck, claimkey, keyclaim]
permissions:
  TxCrates.admin.crates:
    description: Access to /crates
  TxCrates.admin.crate:
    description: Access to /crate <crate id>
  TxCrates.admin.key:
    description: Access to /crate key <player> <crate> [amount]
  TxCrates.admin.edit:
    description: Access to edit crate prizes.
  TxCrates.break:
    description: Access to break crates.